Estruturação da parte lógica base da aplicação
LiuBergaria/contactmi-laravel pull request #2
Opened 2020-12-08 15:24 UTC by LiuBergaria

- Criado toda base de controllers, models, services, migrations, seeders e repositories de contatos.
- Adicionado os providers
- Adicionado uma abstração para retorno com contatos no Controller
- Criado um ServiceResponse padrão.
- Algumas reestruturações mais básicas.
- Agora a home usa contatos reais cadastrados do usuário (exceto as fotos).

2020-12-09 11:15 UTC, eduardohenriquesousasilva commented on app/Http/Controllers/Auth/RegisterController.php
> +use App\Models\User;
Existe uma extensão pro vscode que faz a ordenação dos use, que estão sendo utilizados na classe, nós utlizamos assim até mesmo apra eviar conflito toda vez que alguém adiciona um use novo na classe.

Pode verificar essa questão da ordenação por favor?

2020-12-09 11:17 UTC, eduardohenriquesousasilva commented on app/Http/Controllers/ContactController.php
> +use App\Services\Contracts\ContactServiceInterface;
Ordenação, conforme comentando anteriormente na RegisterController

2020-12-09 11:20 UTC, eduardohenriquesousasilva commented on app/Http/Controllers/ContactController.php
> +        $this->middleware('auth');
Nós não utilizamos a definição do middleware dentro da controller, imagine o cenário que vc possui um método nesta controller que será consumido sem autenticação, ou utilizando outro tipo de autenticação? Por colocar co midlleware no construtor da classe vc teria problemas.

Procure na doc do Laravel sobre como atribuir o middleware no arqivo de rotas, lá onde realiza a definição das rotas.

2020-12-09 11:22 UTC, eduardohenriquesousasilva commented on app/Http/Controllers/ContactController.php
> +    private $service;
uma sugestão é não chamar a variável de apenas $service, com esse nome sabemos que é uma service mas não do que a não ser que a gente olhe aqui na declaração da prop ou no construtor... por isso creio que o nome $contactService pode ficar melhor no decorrer do código, o que acha?

2020-12-09 11:22 UTC, eduardohenriquesousasilva commented on app/Http/Controllers/Controller.php
>  use Illuminate\Foundation\Validation\ValidatesRequests;
Ordenação, conforme comentando anteriormente na RegisterController

2020-12-09 11:23 UTC, eduardohenriquesousasilva commented on app/Http/Controllers/Controller.php
> +        $contactService = App::make('App\Services\Contracts\ContactServiceInterface');
aqui nesta linha se não me engano vc pode usar uma forma mais simples de instanciar a service: app(ContactServiceInterface::class), mas não pode esquecer de fazer o use dela, ai não precisa passar este path inteiro

2020-12-09 11:25 UTC, eduardohenriquesousasilva commented on app/Http/Controllers/Controller.php
> +    public function viewWithContacts($view = null, $data = [], $mergeData = [])
Utilizar tipagem de dados nos argumentos e no retorno do método sempre que possivel

2020-12-09 11:29 UTC, eduardohenriquesousasilva commented on app/Models/Contact.php
> +        return $this->hasMany('App\Models\ContactPhone', 'id_contact', 'id');
Aqui uma sugestão é utilar o use das models,  eai nos relacionamentos vc pode usar apenas ContactPhone::class, por exemplo

2020-12-09 11:31 UTC, eduardohenriquesousasilva commented on app/Models/Contact.php
> +    /**
Uma sugestão em relação as models e colocar as definições dela aqui que são os atributos

$fillable e $casts

2020-12-09 11:37 UTC, LiuBergaria commented on app/Http/Controllers/ContactController.php
> +        $this->middleware('auth');
Sim sim, essa questão eu já matei num commit posterior utilizando o .group

2020-12-09 11:47 UTC, eduardohenriquesousasilva requested changes
Verifiquei o PR, adicionei alguns comentários explicando algumas coisas, fazendo alguma sugestões, tentei ilustrar os motivos dos comentários e etc, qualquer dúvida fique a vontade para me chamar  e fazermos uma call ok?

Valeu

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on app/Models/ContactEmail.php
> +    public $timestamps = false;
Uma sugestão em relação as models e colocar as definições dela aqui que são os atributos
$fillable e $casts

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on app/Models/ContactPhone.php
> +    public $timestamps = false;
Uma sugestão em relação as models e colocar as definições dela aqui que são os atributos
$fillable e $casts

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on app/Models/User.php
>  use Illuminate\Contracts\Auth\MustVerifyEmail;
Ordenação, conforme comentando anteriormente na RegisterController

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on app/Repositories/ContactEmailRepositoryEloquent.php
> +use App\Repositories\Contracts\ContactEmailRepository;
Ordenação, conforme comentando anteriormente na RegisterController

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on app/Repositories/ContactPhoneRepositoryEloquent.php
> +use App\Repositories\Contracts\ContactPhoneRepository;
Ordenação, conforme comentando anteriormente na RegisterController

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on app/Repositories/ContactRepositoryEloquent.php
> +use App\Repositories\Contracts\ContactRepository;
Ordenação, conforme comentando anteriormente na RegisterController

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on app/Services/Contracts/ContactServiceInterface.php
> +    public function getAllByUserId(int $userId);
Sugiro aplicar o a tipagem do retorno do método sempre que possivel

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on app/Services/ContactEmailService.php
> +    private $repository;
Conforme comentei em um caso anterior recomendo declarar a propriedade como $contactEmailRepository, para em qualquer parte da classe conseguirmos identificar qual repository é a prop

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on app/Services/ContactPhoneService.php
> +    private $repository;
Conforme comentei em um caso anterior recomendo declarar a propriedade como $contactPhoneRepository, para em qualquer parte da classe conseguirmos identificar qual repository é a prop

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on app/Services/ContactService.php
> +    private $repository;
Conforme comentei em um caso anterior recomendo declarar a propriedade como $contactRepository, para em qualquer parte da classe conseguirmos identificar qual repository é a prop

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on app/Services/ContactEmailService.php
> +use App\Services\Contracts\ContactEmailServiceInterface;
Ordenação, conforme comentando anteriormente na RegisterController

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on app/Services/ContactPhoneService.php
> +use App\Services\Contracts\ContactPhoneServiceInterface;
Ordenação, conforme comentando anteriormente na RegisterController

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on app/Services/ContactService.php
> +use App\Services\Contracts\ContactServiceInterface;
Ordenação, conforme comentando anteriormente na RegisterController

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on app/Services/ContactService.php
> +class ContactService implements ContactServiceInterface
Uma sugestão na service é realizar o extends de uma BaseService como fazemos lá no nosso projeto, nele por exemplo vc pode ter o metódo padrão de retorno de erros, e utilizar ele de forma bem automática no seu catch

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on app/Services/ContactService.php
> +    public function getAllByUserId(int $userId)
Utilizar a tipagem no retorno do método no caso aqui ServiceResponse, precisaria mudar a assinatura do método na interface também

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on routes/web.php
>  Route::get('/', 'HomeController@index')->name('home');
Sobre o comentário que fiz em relação ao middleware estar na controller, ele pode ser adicionado diretamente aqui, agrupando as rotas para colocar o mesmo middleware em vários ou de forma isolada também

2020-12-09 11:47 UTC, eduardohenriquesousasilva commented on composer.json
> +        "prettus/l5-repository": "^2.7"
Uma sugestão importante, é lembrar sempre de travar as versões de pacotes instalados como dependência da aplicação principalmente, a mudança de versão de um pacote pode fazer a aplicação quebrar por isso esse cuidado é importante

2020-12-09 11:47 UTC, eduardohenriquesousasilva requested changes
Verifiquei o PR, adicionei alguns comentários explicando algumas coisas, fazendo alguma sugestões, tentei ilustrar os motivos dos comentários e etc, qualquer dúvida fique a vontade para me chamar  e fazermos uma call ok?

Valeu

2020-12-09 11:47 UTC, eduardohenriquesousasilva requested changes
Verifiquei o PR, adicionei alguns comentários explicando algumas coisas, fazendo alguma sugestões, tentei ilustrar os motivos dos comentários e etc, qualquer dúvida fique a vontade para me chamar  e fazermos uma call ok?

Valeu

2020-12-09 11:48 UTC, LiuBergaria commented on app/Http/Controllers/Auth/RegisterController.php
> +use App\Models\User;
Vou instalar aqui. No caso vocês usam a função sortOnSave?

2020-12-09 11:52 UTC, eduardohenriquesousasilva commented on app/Http/Controllers/Auth/RegisterController.php
> +use App\Models\User;
Eu utilizo ela para fazer o sort quando eu façoo import, é importante isso pra evitar conflito e ficar constando como modificações em todos os uses toda vez que alguém adiciona algo sacas?

2020-12-09 11:53 UTC, LiuBergaria commented on app/Http/Controllers/ContactController.php
> +    private $service;
então, em alguns projetos eu uso o padrão de utilizar apenas o nome "service", por exemplo, quando se trata da mesma entidade do controller, geralmente só para uma redução no código na hora de utilizar a service, mantendo esse padrão... mas isso é totalmente questão de padronização do projeto mesmo, por mim, tanto um, quanto o outro fica bom

2020-12-09 11:54 UTC, LiuBergaria commented on app/Http/Controllers/Controller.php
> +        $contactService = App::make('App\Services\Contracts\ContactServiceInterface');
Opa, não sabia dessa, vou fazer a alteração, valeu!

2020-12-10 11:26 UTC, eduardohenriquesousasilva approved these changes

2020-12-10 11:26 UTC, merged